#!/bin/bash

package_name="$(pwd | awk 'BEGIN { FS = "/" } ; {print $NF}')"
prefix="/usr/local"
stow_prefix="${prefix}/stow"
install_dir="${stow_prefix}/${package_name}"

./configure --prefix="$prefix" \
    && make PREFIX="$prefix" \
    && sudo make install prefix="$install_dir" \
    && cd "${stow_prefix}" \
    && sudo stow -vv "$package_name"

